### ISSUE TITLE
When Highlighting a Cell the whole row is an unsightly black - not like the examples

### ISSUE THREAD

**Issue by L-K-Mist** [paulhodel/jexcel-with-vue#2]
I'm using this with the Vue sample.

Attached is a gif of what I'm seeing. Did a search here to see if anyone else has encountered this, but no obvious keyword matches.

![snag with jExcel](https://user-images.githubusercontent.com/22072669/65428716-251f5280-de15-11e9-9e5b-34aab1635333.gif)

Have you seen this before?

**Comment by L-K-Mist** [comment]
Oops, I think I posted in the wrong place with this being more of a general Jexcel issue than specific to your vue example.  

If there are others, I was able to fix by modifying the .selected class like so:

```
tr.selected {
  background-color: white !important;
  color: black !important;
}
```

**Comment by pphod** [comment]
I guess there a conflict with any other library since I have never seem that. But, glad that you find a solution.
